sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - "node"
before_install:
  - cd site
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
script:
  - npm run lint
  - npm t
deploy:
  - npm run deploy

